repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: pep8
        name: pep8
        entry: poetry run flake8
        language: system
        types:
          - python
  - repo: local
    hooks:
      - id: typing
        name: typing
        entry: poetry run mypy
        language: system
        types:
          - python
  - repo: local
    hooks:
      - id: black
        name: format::black
        entry: poetry run black
        language: system
        types:
          - python
      - id: isort
        name: format::isort
        entry: poetry run isort
        language: system
        types:
          - python
  - repo: local
    hooks:
      - id: security
        name: security
        entry: poetry run bandit
        language: system
        types:
          - python
        exclude: ^tests/
      - id: complexity
        name: complexity
        entry: poetry run xenon --max-absolute B --max-modules A --max-average A
        language: system
        types:
          - python
