name: Python application CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-coding:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Test PEP8
        run: |
          poetry run flake8 src tests
      - name: Test typing
        run: |
          poetry run mypy src tests
      - name: Test formatting
        run: |
          poetry run black --check src tests
          poetry run isort --check src tests
  test-unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Test unit test
        run: |
          poetry run pytest -v --cov=src --cov-report=term-missing
  test-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install poetry
          poetry install
      - name: Test security
        run: |
          poetry run bandit -r src
      - name: Test complexity
        run: |
          poetry run xenon --max-absolute B --max-modules A --max-average A src tests
